#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo 's6-overlay init require(/app/www/public/startup.php) ->';
s6-setuidgid abc php -r "require '/app/www/public/startup.php';"
echo 's6-overlay init require(/app/www/public/startup.php) <-';

# permissions
lsiown -R abc:abc \
    /config