# Deploy a development environment for Dockwatch
---
services:
    dockwatch:
        container_name: dw_develop
        networks:
            isolated_nw:
                ipv4_address: 172.28.0.5
        depends_on:
            - socket-proxy # -> Comment if not using socket proxy
        environment:
            - PUID=1000
            - PGID=990 # -> Change to your docker group (cat /etc/group | grep docker)
            - TZ=Etc/UTC
            - DOCKER_HOST=tcp://socket-proxy:2375
            - DISABLE_IPV6=1
        ports:
            - 10000:80/tcp
            - 10001:8081/tcp # -> phpmyadmin port
        volumes:
            - ./.data/dockwatch/config:/config
            - ../root/app/www/public:/app/www/public # -> Link local files for development
            # - /var/run/docker.sock:/var/run/docker.sock # -> Uncomment if not using socket proxy
        restart: unless-stopped
        image: ghcr.io/notifiarr/dockwatch:local # -> Run `sh docker/build.sh` in root directory first

    # -> Simple nginx container to test reverse proxy setups (optional)
    # nginx:
    #     container_name: dw_nginx
    #     networks:
    #         isolated_nw:
    #             ipv4_address: 172.28.0.10
    #     depends_on:
    #         - dockwatch
    #     environment:
    #         - PUID=1000
    #         - PGID=1000
    #         - TZ=Etc/UTC
    #     ports:
    #         - 10001:80/tcp
    #     volumes:
    #         - ./nginx.conf:/config/nginx/site-confs/default.conf:ro
    #     restart: unless-stopped
    #     image: ghcr.io/linuxserver/nginx:1.28.2

    # -> Docker socket proxy
    socket-proxy:
        privileged: true
        container_name: dw_socket_proxy
        networks:
            isolated_nw:
                ipv4_address: 172.28.0.15
        environment:
            - ALLOW_START=1
            - ALLOW_STOP=1
            - ALLOW_RESTARTS=1
            - POST=1
            - CONTAINERS=1
            - IMAGES=1
            - NETWORKS=1
            - VOLUMES=1
            - EXEC=1
        ports:
            - 127.0.0.1:2375:2375
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        image: tecnativa/docker-socket-proxy

networks:
    isolated_nw:
        name: dw_isolated_nw
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
                  gateway: 172.28.0.1
