#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# https://github.com/linuxserver/docker-mariadb/tree/305952458ca73abad02a8cd3b3fb6a30df58d97c/root/etc/s6-overlay/s6-rc.d

if [[ -f "/config/tmp/update.txt" || -f "/config/tmp/restart.txt" ]]; then
    exit 0
fi

# remove orphan pid file
if [[ -f /run/mysqld/mysqld.pid ]]; then
    rm -f /run/mysqld/mysqld.pid
fi

# install mysql db
if [ ! -f "/config/.created-db" ]; then
    echo "**** installing database ****"
    mariadb-install-db --user=abc --datadir=/config/database/mysql &>/dev/null
    touch /config/.created-db
fi

# run mysql db
echo "**** running database ****"
mkdir -p /run/mysqld && chown abc:abc /run/mysqld
s6-setuidgid abc \
    /usr/bin/mariadbd-safe \
    --datadir=/config/database/mysql \
    --pid-file=/run/mysqld/mysqld.pid \
    --skip-networking=OFF \
    --user=abc >/dev/null 2>&1 &

echo "waiting for mysqld.."
while ! mariadb-admin ping --silent; do
    sleep 5
done
